name: 'CI Unit Test'
description: 'Checkout, install deps, and run unit tests'
inputs:
  python-version:
    required: false
    default: "3.11"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - uses: kprasadpn/github-platform-workflows/.github/actions/setup-python-env@main
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run unit tests
      shell: bash
      run: pytest tests/ -v
