name: CI Build Template

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      python-version:
        required: false
        type: string
        default: "3.11"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: kprasadpn/github-platform-workflows/.github/actions/ci-build@main
        with:
          app-name: ${{ inputs.app-name }}
          python-version: ${{ inputs.python-version }}
