name: CI Unit Test Template

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.11"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: kprasadpn/github-platform-workflows/.github/actions/ci-unit-test@main
        with:
          python-version: ${{ inputs.python-version }}
