name: GHAS CodeQL Analysis Template

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      build-mode:
        required: false
        type: string
        default: "none"

jobs:
  codeql-analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v4

      - uses: kprasadpn/github-platform-workflows/.github/actions/codeql-init@main
        with:
          language: ${{ inputs.language }}
          build-mode: ${{ inputs.build-mode }}

      - uses: kprasadpn/github-platform-workflows/.github/actions/codeql-analyze@main
        with:
          language: ${{ inputs.language }}
